App\Entity\Message:
  properties:
    content:
      - NotBlank:
          message: "Le message ne peut pas être vide"
      - Length:
          min: 8
          max: 2000
          minMessage: "Votre message doit faire au moins {{ limit }} caractères"
          maxMessage: "Votre message doit faire au plus {{ limit }} caractères"

App\Entity\User:
  properties:
    email:
      - Email:
          message: "L'email {{ value }} n'est pas valide"
      - NotBlank:
          message: "L'email ne peut pas être vide"
